import Link from "next/link";
import React from "react";

export const metadata = {
  title: "About Meta",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function About() {
  // throw new Error("Not Today")
  return (
    <>
      <h1>About</h1>
      <Link href="/">Link to Home Page</Link>
    </>
  );
}
